import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Cart from "@/components/cart/cart";
import { GlobalContextProvider } from "@/redux/Provider";

import Footer from "@/components/Footer/footer";
import { Next13NProgress, Link } from "nextjs13-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-NoirProRegular`}>
        {/* <GlobalContextProvider>
          
          
          {children}
        </GlobalContextProvider> */}
        <GlobalContextProvider>
          {/* <Cart /> */}
          {children}

          <Footer />
          <Next13NProgress color="red" height={5} />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
